### ISSUE TITLE
Computing content and style factors

### ISSUE THREAD

**Issue by Hayoung93** [Seung-Hun-Lee/DRANet#1]
Hi, I'm a bit confused about computing content and style factors.

https://github.com/Seung-Hun-Lee/DRANet/blob/d7eb779f9abab8f8ed1fbab501b43b50a3a2218b/models/DRANet.py#L74-L75
The content factor is extracted through the separator S in the paper, however, it seems that the style factor is extracted through S in this code.

Please let me know if it doesn't really matter or if I missed something. Thank you!

**Comment by Seung-Hun-Lee** [comment]
You can also try (maybe you need to adjust the hyperparameters):
**contents**[key] = self.conv(features[key])
 **styles**[key] = features[key] - **contents**[key]

It works well, but we find experimentally that the formulation in our code performs a little better. 
I think it is not that important whether we encode content or style via some networks.

Thank you.
